# Generated by Django 5.1.3 on 2024-11-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribemodel',
            name='audioid',
            field=models.TextField(default='jhelo'),
            preserve_default=False,
        ),
    ]
